version: '2.1'
services:
  postgres:
    container_name: postgres-exceptionmanager-it
    image: sdcplatform/ras-rm-docker-postgres
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=200"]
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    container_name: rabbitmq-exceptionmanager-it
    image: rabbitmq:3.6.10-management
    ports:
      - "34369:4369"
      - "55672:25672"
      - "35671:5671"
      - "35672:5672"
      - "46671:15671"
      - "46672:15672"
    volumes:
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      - ./definitions.json:/opt/definitions.json:ro
